CREATE TABLE IF NOT EXISTS listings(
    listing_id  BIGINT,
    listing_name VARCHAR,
    host_id BIGINT,
    host_identity_verified VARCHAR,
    host_name NAME,
    neighbourhood_group VARCHAR,
    neighbourhood VARCHAR,
    lat FLOAT,
    long FLOAT,
    country VARCHAR,
    country_code VARCHAR,
    instant_bookable BOOLEAN,
    cancellation_policy VARCHAR,
    room_type VARCHAR,
    construction_year INT,
    price MONEY,
    service_fee MONEY,
    minimum_nights INTEGER,
    number_of_reviews INTEGER,
    last_review TIMESTAMP,
    reviews_per_month FLOAT,
    review_rate_number FLOAT,
    calculated_host_listings_count INTEGER,
    availability_365 INTEGER,
house_rules VARCHAR,
    license VARCHAR
);
