CREATE TABLE IF NOT EXISTS listings(
    id SERIAL PRIMARY KEY,
    listing_id  BIGINT,
    listing_name VARCHAR,
    host_id BIGINT,
    host_identity_verified VARCHAR,
    host_name NAME,
    neighbourhood_group VARCHAR,
    neighbourhood VARCHAR,
    lat FLOAT,
    long FLOAT,
    country VARCHAR,
    country_code VARCHAR,
    instant_bookable BOOLEAN,
    cancellation_policy VARCHAR,
    room_type VARCHAR,
    construction_year FLOAT,
    price MONEY,
    service_fee MONEY,
    minimum_nights FLOAT,
    number_of_reviews FLOAT,
    last_review TIMESTAMP,
    reviews_per_month FLOAT,
    review_rate_number FLOAT,
    calculated_host_listings_count FLOAT,
    availability_365 FLOAT,
house_rules VARCHAR,
    license VARCHAR
);
